config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  
  root to: 'homes#top'
  
  get 'home/about' => 'homes#about', as: 'about'
  
  resources :books
  
  resources :users, only: [:show, :edit, :index, :destroy, :update]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  
  has_many :books, dependent: :destroy
  
  validates :name, length: { minimum: 2, maximum: 20}, uniqueness: true
  
  validates :introduction, length: { maximum: 50}
  
  def get_profile_image(width,height)
      
    unless profile_image.attached?
    
      file_path = Rails.root.join('app/assets/images.1/no_image.jpg')
    
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    
    end
    
      profile_image.variant(resize_to_limit: [width,height]).processed
  
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :authenticate_user!, except: [:top,:about]
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
      
      flash[:notice] = "Signed in successfully."

      user_path(current_user.id)
      
    end
    
    def after_sign_out_path_for(resource)
      
      flash[:notice] = "Signed out successfully."

       root_path

    end

  protected

  def configure_permitted_parameters
      
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    
  end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    
    @books = Book.all
    
    @book_new = Book.new
    
    @user = current_user
    
    @book = Book.new
    
  end

  def show
    
    @book = Book.find(params[:id])
    
    @user = @book.user

    @book_new = Book.new

  end
  
  def create
    
    @book = Book.new(book_params)
    
    @book.user_id = current_user.id
    
    if @book.save
    
      flash[:notice] = "You have created book successfully."
    
      redirect_to book_path(@book.id)
    
    else
      
      @books = Book.all
    
      @book_new = Book.new
    
      @user = current_user
      
      render :index
    
    end
    
  end
  
  
  def edit
    
    is_matching_login_user
    
    @book = Book.find(params[:id])
    
  end
  
  def update
    
    is_matching_login_user
    
    @book = Book.find(params[:id])
    
    if @book.update(book_params)
    
    flash[:notice] = "You have updated book successfully."
    
    redirect_to book_path(@book.id)
    
    else
    
    
      
    render :edit
    
    end
    
  end
  
  def destroy
    
    book = Book.find(params[:id])
    
    book.destroy

    redirect_to '/books'
    
  end

  private

  def is_matching_login_user

    book = Book.find(params[:id])
    
    unless book.user_id == current_user.id
  
      redirect_to "/books"
  
    end
    
  end

  def book_params

    params.require(:book).permit(:title, :body)
  
  end
 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    
    @book = Book.new
    
    @user =User.find(params[:id])
    
    @books = @user.books
    
    @book_new = Book.new 
    
  end
  
  def cleate
  end
  
  def index
    
    @user = current_user
    
    @users = User.all
    
    @book_new = Book.new 
    
  end
  
  def edit
    
    is_matching_login_user
    
    @user = User.find(params[:id])
    
  end
  
  def update
    
    is_matching_login_user
    
    @user = User.find(params[:id])
    
    if @user.update(user_params)
    
      flash[:notice] = "You have updated user successfully."
    
      redirect_to user_path(@user.id)
    
    else
      
      render :edit
    
    end
  
  end

  private

  def  is_matching_login_user
  
    user = User.find(params[:id])
   
    unless user.id == current_user.id
    
      redirect_to user_path(current_user.id)
    
    end
    
  end

  def user_params
  
    params.require(:user).permit(:name, :introduction, :profile_image)
  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h1>User info</h1>
    
  <%= image_tag user.get_profile_image(100,100) %>
  
  <table>
    
    <tr>
      <th>name</th>
      <td><%= user.name %></td>
    </tr>
    
    
    
    <tr>
      <th>introduction</th>
      <td><%= user.introduction %></td>
    </tr>
  
  </table>
  
    <%= link_to(edit_user_path(user.id),class: "btn btn-outline-secondary btn-block") do %>
    
    <i class="fa-solid fa-user-cog"></i>
    
    <% end %>

<h1>New book</h1>

<%= form_with model: book_new, url: '/books', method: :post do |f| %>

  <h4>Title</h4>
  
  <%= f.text_field :title %>
  
  <h4>Opinion</h4>
  
  <%= f.text_area :body %><br>

  <button type="submit" class="btn btn-success">Create Book</button>

<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<h3>

  <% if @book.errors.any? %>

    <%= @book.errors.count %> errors prohibited this obj from being saved:
  
    <ul>
  
      <% @book.errors.full_messages.each do |message| %>
  
        <li><%= message %></li>
    
      <% end %>
  
    </ul>

  <% end %>

</h3>

<%= form_with model: @book do |f| %>

  <label for="inputTitle">Title</label></br>

  <%= f.text_field :title, autofocus: true, id:"inputName" %></br>
  
  <label for="inputBody">Opinion</label></br>
  
  <%= f.text_field :body %></br>
  
  <button type="submit" class="btn btn-success">Update Book</button>
  
<% end %>

<%= link_to "Show", book_path(@book) %>

<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
    
  <%= @book.errors.count %> errors prohibited this obj from being saved:
        
  <ul>
        
    <% @book.errors.full_messages.each do |message| %>
        
      <li><%= message %></li>
    
    <% end %>
      
  </ul>
      
<% end %>

<div class="container">
      
  <div class="row">
    
      <div class="col-md-3">

        <%= render 'list', user: @user, book_new: @book_new %>
        
      </div>
      
      <div class="col-md-8 offset-md-1">
        
        <h1>Books</h1>
        
        <table>
          
          <thead>
          
            <tr>
            
              <th></th>
          
              <th>Title</th>
            
              <th>Opinion</th>
            
              <th colspan="3"></th>
            
            </tr> 
          
          </thead>
        
          <tbody>
            
            <% @books .each do |book| %>
          
              <tr>
            
                <td>
                  
                  <%= link_to user_path(book.user.id) do %>
                      
                    <%= image_tag book.user.get_profile_image(100,100) %>
                  
                  <% end %>
                  
                </td>
                  
                <td><%= link_to book.title, book_path(book.id) %></td>
                
                <td><%= book.body %></td>
                  
              </tr>
                  
            <% end %>
                  
          </tbody>
        
        </table>
        
      </div>
      
    </div>
  
  </div>

app/views/books/show.html.erb
<%= flash[:notice] %>

<div class="container">
      
  <div class="row">
    
    <div class="col-md-3">
        
      <%= render 'list', user: @user, book_new: @book_new %>
                
    </div>
        
    <div class="col-md-8 offset-md-1">
        
      <h1>Book detail</h1>
        
      <table>
          
        <tr>
          
          <td>
                
            <%= link_to user_path(@book.id) do %>
                      
              <%= image_tag @book.user.get_profile_image(100,100) %></br>
                        
            <% end %>
                
            <%= link_to @user.name, user_path(@book.user) %>
                
          </td>
                    
          <td><%= link_to @book.title, book_path(@book) %></td>
                
          <td><%= @book.body %></td>
                
            <% if @book.user == current_user %>
                        
              <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
                
              <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
                
            <% end %>
              
        </tr>
                
      </table>
            
    </div>
            
  </div>  
          
</div>
      
      

app/views/homes/about.html.erb
<div class="container">
    
  <div class="row">
      
      <h1 class="px-3 mx-auto">
          
          Welcom to
          <i class="fa-solid fa-book"></i>
          <strong>Bookers!</strong>
          
      </h1>
      
  </div>
    
</div>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!!</h1>
     
        <p>In  <i class="fa-solid fa-book"></i><strong>Bookers,</strong>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>


</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/95b647ef78.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class= "nav-link text-light">
              <%= link_to(user_path(current_user.id), class: "text-light") do %>
              <strong><i class="fa-solid fa-home"></i><span>Home</span></strong>
              <% end %>
              </li>
              <li class= "nav-link text-light">
              <%= link_to(users_path, class: "text-light") do %>
              <strong><i class="fa-solid fa-users"></i><span>Users</span></strong>
              <% end %>
              </li>
              <li class= "nav-link text-light">
              <%= link_to(books_path, class: "text-light") do %>
              <strong><i class="fa-solid fa-book-open"></i><span>Books</span></strong>
              <% end %>
              </li>
              <li class= "nav-link text-light">
              <%= link_to(destroy_user_session_path, method: :delete, class: "text-light") do %>
              <strong><i class="fa-solid fa-sign-out-alt"></i><span>Log out</span></strong>
              <% end %>
              </li>
            <% else %>
              <li class= "nav-link text-light">
              <%= link_to(root_path, class: "text-light") do %>
              <strong><i class="fa-solid fa-home"></i><span>Home</span></strong>
              <% end %>
              </li>
            
              <li class= "nav-link text-light">
              <%= link_to(about_path, class: "text-light") do %>
              <strong><i class="fa-solid fa-link"></i><span>About</span></strong>
              <% end %>
              </li>
              
              <li class= "nav-link text-light">
              <%= link_to(new_user_registration_path, class: "text-light") do %>
               <strong><i class="fa-solid fa-user-plus"></i><span>Sign up</span></strong>
              <% end %>
              </li>
              
              <li class= "nav-link text-light">
              <%= link_to(new_user_session_path, class: "text-light") do %>
               <strong><i class="fa-solid fa-sign-in-alt"></i><span>Log in</span></strong>
              <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <%= flash[:notice] %>
      <%= yield %>
    </main>
    <footer>
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  
  <div class="row">
    

    <div class="mx-auto">
      
      <h1>User info</h1>

      <% if @user.errors.any? %>
      
        <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
        
        <ul>
        
          <% @user.errors.full_messages.each do |message| %>
        
            <li><%= message %></li>
          
          <% end %>
        
        </ul>
      
        <% end %>
          
      
      
      <%= form_with model: @user do |f| %>
      
        <label for="inputTitle">Name</label></br>
      
        <%= f.text_field :name, autofocus: true, id:"inputName" %></br>
        
        <label for="inputImage">Image</label></br>
        
        <%= f.file_field :profile_image, accept: "image/*" %></br>
        
        <div id="new-image"></div>  #追記

        
        <label for="inputBody">Introduction</label></br>
        
        <%= f.text_area :introduction %></br>
        
         <button type="submit" class="btn btn-success">Update User</button>
        
      <% end %>

    </div>
    
  </div>
  
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
      
  <div class="row">
    
    <div class="col-md-3">

      <%= render '/books/list', user: @user, book_new: @book_new %>
      
    </div>
  
    <div class="col-md-8 offset-md-1">

      <h1>Users</h1>
      
      <table>
        
        <thead>
        
          <tr>
        
            <th>image</th>
          
            <th>name</th>
          
            <th colspan="3"></th>
          
          </tr> 
        
        </thead>
      
        <tbody>
          
          <% @users .each do |user| %>
        
            <tr>
          
              <td><%= image_tag user.get_profile_image(100,100) %></td>
        
              <td><%= user.name %></td>
              
              <td><%= link_to "Show", user_path(user.id) %></td>
              
            </tr>
        
          <% end %>
          
        </tbody>
      
      </table>
    
    </div>

  </div>
  
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>

<div class="container">
      
  <div class="row"> 
    
    <div class="col-md-3">
        
      <%= render "/books/list", user: @user, book_new: @book_new %>
        
    </div>

    <div class="col-md-8 offset-md-1">
        
      <h1>Books</h1>

      <table>
            
        <thead>
              
           <th>Title</th>
           <th>Opinion</th>
          
        </thead>
        
        <tbody>
            
          <% @books.each do |book| %>
                
            <tr>
                
              <td>
                      
                <%= link_to user_path(book.user.id) do %>
                  
                  <%= image_tag book.user.get_profile_image(100,100) %>
                      
                <% end %>
                  
              </td> 
                
              <td><%= link_to book.title, book_path(book.id) %></td>
                  
              <td><%= book.body %></td>
                
            </tr>
            
          <% end %>
              
        </tbody>
                
      </table>
                
    </div>
  
  </div>

</div>